---
output: pdf_document
---

### Accessibility of Programs

#### Transportation

- Collaborate with public transportation authorities to improve transportation options
- Situate significant programs with high capacity near public transportation
- Inform participants of Student Ventra Cards, which are issued in many schools

#### Marketing

- Develop target outreach strategies and marketing efforts to underserved communities 
- Collaborate with community organizations, schools, and local youth-serving agencies

#### Technology

- Provide resources and support for youth who don't have access to necessary technology
- Collaborate with local organizations and libraries to offer computer labs, Internet access, and loaner devices for program participants

#### Data Collection

- Monitor program participation, demographics, and outcomes, i.e. via a sign-up or sign-in sheet 
- Conduct regular evaluations to assess program effectiveness and identify communities that need more outreach
- Collect feedback from participants and organizations


### Community Ties

Strengthen partnerships with schools, community organizations, and local businesses to expand program reach and resources.

#### Staff Professional Development

- Collaborate with community partners to provide staff professional development opportunities
- Focus training on inclusiveness, diversification and effective communication to serve the various needs of Chicago's youth

#### Community & Social Spaces

- Establish community spaces in urban areas for youth to socialize and programs to be held
- Consider offering affordable or subsidized meals in programs and eliminate financial barriers

#### Focus Groups

- Conduct regular focus groups with youth and their families to gather feedback on program preferences, barriers to participation, etc. 
- Incorporate their input into program planning and decision-making processes

#### Childcare Needs

- Engage and communicate with parents, caregivers, and guardians during programs and as active partners in the decision-making process
- Collaborate with local organizations to provide affordable or free childcare options during program hours

### Professional Development

#### Jobs

- Foster partnerships with local businesses and organizations to create job opportunities, internships, or apprenticeships

#### Supplementing Academic Achievement

- Develop a department or programs that offer academic support and support youth in program selection
- Recognize participants for participation or other achievements through social media or on the website

#### Pathways to Mentorship

- Create opportunities for youth to engage with mentors who can provide guidance, support, and networking opportunities, promoting upward mobility and personal growth

